apiVersion: v2
name: intel-gpu-device-plugin
version: 0.0.0
dependencies:
  - name: intel-device-plugins-operator
    version: 0.31.1
    repository: https://intel.github.io/helm-charts
  - name: intel-device-plugins-gpu
    version: 0.31.0
    repository: https://intel.github.io/helm-charts
