apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn-ephemeral

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-music
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  nfs:
    path: /mnt/data/music
    server: nas.internal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-music
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: plex-music

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-movies
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  nfs:
    path: /mnt/media/movies
    server: nas.internal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: plex-movies

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-series
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  nfs:
    path: /mnt/media/series
    server: nas.internal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-series
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: plex-series
