pvc:
  pvcName: radicale-data
  storageRequest: 128Mi
  moverSecurityContext:
    runAsUser: 2999
    runAsGroup: 2999

global:
  createDefaultServiceAccount: false

app-template:
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 2999
      runAsGroup: 2999
  configMaps:
    radicale:
      data:
        config: |
          [server]
          hosts = 0.0.0.0:5232

          [auth]
          type = htpasswd
          htpasswd_filename = /config/users
          htpasswd_encryption = bcrypt

          [storage]
          filesystem_folder = /data/collections
  externalSecrets:
    radicale:
      secretStoreRef:
        name: bitwarden
        kind: ClusterSecretStore
      data:
        - secretKey: users
          remoteRef:
            key: RADICALE_AUTH_DB
  controllers:
    radicale:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        radicale:
          image:
            repository: tomsquest/docker-radicale
            tag: 3.8.3.0@sha256:a3b1b452f4bc3d1aee43015b85bc2d9ee5de0ff7e96d5d2b47f1d889aa682409
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          env:
            TAKE_FILE_OWNERSHIP: "false"
          probes:
            startup:
              enabled: true
            liveness:
              enabled: true
            readiness:
              enabled: true
  service:
    radicale:
      controller: radicale
      ports:
        http:
          port: 5232
  ingress:
    radicale:
      className: external
      hosts:
        - host: radicale.neils.house
          paths:
            - path: /
              service:
                identifier: radicale
                port: http
  persistence:
    config:
      type: configMap
      name: radicale
      globalMounts:
        - path: /config/config
          subPath: config
          readOnly: true
    data:
      existingClaim: radicale-data
    users:
      type: secret
      name: radicale
      globalMounts:
        - path: /config/users
          subPath: users
          readOnly: true
