global:
  createDefaultServiceAccount: false

app-template:
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
  controllers:
    piper:
      containers:
        piper:
          image:
            repository: docker.io/rhasspy/wyoming-piper
            tag: 2.5.2@sha256:7d39aafac409c2b6b09d999ed04d84c311d632e558b35baa60fad6aac722af7a
          args:
            - --voice
            - en_US-lessac-medium
            - --data-dir
            - /data
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          probes:
            startup:
              enabled: true
            liveness:
              enabled: true
            readiness:
              enabled: true
  service:
    piper:
      controller: piper
      ports:
        http:
          port: 10200
  persistence:
    data:
      type: emptyDir
