global:
  createDefaultServiceAccount: false

app-template:
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
  controllers:
    piper:
      containers:
        piper:
          image:
            repository: docker.io/rhasspy/wyoming-piper
            tag: 2.4.2@sha256:72ee1b06b062cb14f4a70de002eb420a068efd5a7a8cb7620be6bf600307f867
          args:
            - --voice
            - en_US-lessac-medium
            - --data-dir
            - /data
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          probes:
            startup:
              enabled: true
            liveness:
              enabled: true
            readiness:
              enabled: true
  service:
    piper:
      controller: piper
      ports:
        http:
          port: 10200
  persistence:
    data:
      type: emptyDir
