apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-api-token: "AgCze7wklj2u3j1s/QlnABXTEq8sktoxFEOuP4Yritv4v+t91bfwUBrAfwlcXwB5PxvMkpRQmtl8F8ipuJBrVvNoNJHyfiUrJNJ3ytok+UrL7Qgd25BYgJpQbY4GsxbAdrYFFTk3MafTNMYWhlkNThb1OGbaedTBKv8q/5eUT3oOxBc6URXvmUKTbB/0caROHT826zCVBcSyZI7tH/4z97LbdprTiDqcEj4zWaQf9iuE7tVWEeAOEw+35W+bgbpGcfGIyaTWLKanaOubobgX+a3r+ip04pW7X3o57CqyniYmZXxBdVifWze1sujg8tUe7KlA3wl146sd06Fng66FPuHd6qAUOzmOPo9H6uhk/qKkWCxwpTd5kdLMhgMh0wQzdz2GtIXJSzhANQH2K8rINGSsyG0UzlxtRvdV2rlcG4nMYSg0BG46SZekCBgyoM+Pf/1HWvBj7Dg7Tj7o3Pg84jpU38Y5Ov3+eRaZ75UVKGEBCAtxikPzTzJIK0den0vKBgzXJElzFgfmApusSfU5Zf6idUonO7Mxx6kqz7AxeXA9JCUvX6N6m/n0UXW1OTxXZEOyadpDeE0+6PBhvMJOfnoENDgDCRZ41AzLPDVDst5NnU8aGDJo/yt47t2ptRk7RZUmZvgSn/dZEwJ7KV//83YhDu6DcS1kWyRLNm8Xizl06EusYDWkJyqqvgiF9KM0aPyrao5pCfO3oiZ4MFLoXybEg+2rjFNKQ3sfuYQuITLtcNfxkMkwefcO"
