apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
spec:
  encryptedData:
    cloudflare-api-token: "AgB8/d601jQBv1p5Cb7w89ztejF9ae2obEmiU45fSVyMondcVnLK1nmG0BA05NTRzIJL+d3wuII/BVb48BpmsSS+xi1qG39YZR93EuLF1Uew2IIDJuNzXEQmLMayzovDLNC+FVsQ9I33AbFk4bOWbAWlFomwZw5uuixuaj9UowfgZSbXDZqmgrsTwb5EVfpBd4z45pJlnye9SllMq0TFn5XvzENIFHkgxikZ1/AqT5gRn5n8EqdYmsOE9HmteVs1ONuN34x2D5WM7oyUKsJQ10F0zNC4cFGa6R2ykFnHNY2b4JKBECcuJQk/y6RoG38SjIKcmwnelEytRSimWGnKktbsvDkTS8rIIlecQi3m6xzt5wl0/0IJcbENbHqDu/9YZ3w+4yxtjKEdY6UxBvpd7q6ZP5RoZDnG+VDHFHxou0muwQE/jm7+9gLSEjqrfFvY9b+s0yJ6Sd6xSFU5tXHlB1C/J3Zex8OuYp/mFUazf58CPnjWzkutVObG4/QVRng4MljSkuWkOtu1M9Ib54a80ITlufP1kPQUrD8uxpLFhnNb5/LYb7F3KzdaE+Y0zHF0bkHmjUixEISoNElLPz/Gqi/EE394PKTt7JaHrzeQ/6CiD8ch67ljLJc39IXRel8vToc1ywPpdumB5nk0nktCjS78ssWEvIKUAh640vcFM/2B6thBax8ASRw+rJu5ML93Vru+Y2LNUCLEujy28+U0empUniMqgK63ZgL/y8WFExtbpB8DNnwLJ5UR"
