apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: kube-system
spec:
  encryptedData:
    cloudflare-api-token: "AgAfhyDOCDEYjSeFYt95dhAMtRL2CWXaftVxBQeX2YVzXjFwhsRmRE17gWWFA5CUSwKbPXVbOVvph5oNLTLXuO7fOIIQmnKnsjLhhQaAKjxusBLCLUng3mxLNBJ6se52XIJ+94eMzPeywoUohSdU3qBZJH1EFKx5GczKPtwasR1rPYgjhMtgdVq6vryafrauzLdwlRnn6JAxszx04qyWYoRAbIQnrMTh5q4GUiZTJaseC0tpK5C7HVXN4uEJghsxK3ab9q3lUfUIX5Zvtl0R3HRFmBQYm69ASjg5OrlvnRoA/JiM6GKo+BYunzvfGQhy+cQ0o/18mM6JCmNRy6SxqiMOOtPWwLsNBKczkCwwD0De0bM4rj22wZaXf9Fjdn68nRkV49QKMcx+Xo7MN4fvVBFvwCR/8PtVu/zNPhtG3tdnszNvxxbD7t+rISJ5hChOrcvZSDICJkO4daWJs1hH8LzPeTcJRmQ9RPAgQMLzSrncs0a9yQdGXbmTYq8bFiHGEM4f1uvkzTyltSEBwIdJa3dhAVTka6PC0U2OBhAZFKq6eEqpr+CK49nev2tUs8ZtgzhAcpbgODcRRF9HkcKOW9TyxfWnz8PUBdtUjtlWE/iDpsfalQUqK1oBlWriC7MOHuqhtDtKyVwbbe1Cp+hUhQ647TRGjBsVGL0UkTTBx25eFZoO9zqlEfJlUstJEW3xQocSR32f2Ta7A5u/PpL/1SNogzflVYM0B0/cAL+Mal+WFWamkCKlerKt"
