apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    extraVolumeMounts:
      - name: ssl
        mountPath: /ssl
    extraVolumes:
      - name: ssl
        secret:
          secretName: wildcard-tls
