apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pocket-id
spec:
  encryptedData:
    ENCRYPTION_KEY: "AgAB+Wykm1BmvWaUsZ4Qtea0XwAts3EQ51tNY00SOLG/3mT6HTHOa2uMNw3ChYhd9dl/1yuX+RSVAJbt3VVkrpX1aLiGkC336B4RYp/qEuiMufmzboXwvGKP9fMWh8DstYaRjiOewjqZ9TfxiRKc82pWQ2xfTd4RY6F3KzFNelue6K2tRpsIH8eMoJgKInpIIW2gh5cCMh4E6UfyJX/IsUv71hpyp0/LnfmLlL2S5Mm7VzQmFSNCt7SOZ/RsiOZsuXCEpE7DFxIXwc5n6VO1ZK6oUgVJmAqBRUH+9F+z/Siyj14zEKTKdOq6+0pLMMgvRRX00hd7eVLUiMSj7nyvLPNd1Mc7L2CLQ9JozYOIjWtMvBNHQtscpmRJBOdYqoeyQJsC4NJfLDBCzH+g0VY4XCZnB2hYnhF27DDih2ZnnTIoXrMmFG916bLGTsCqthQuLarmqSdNawmqYIeFk2n+Bg/RfwB359Mo4MLqNUDww7BqBAq08EJZJnNUQ5QJTucZOktdDcFG1/SjMTA5nXkPgP6RERYJWZyON0QKgllFPPX9r5IE/RDT690YpiB87hCeomzH/uN8gt0puO0ajZA9wj96l647QZTyWpzCjRyebI8J/qsAwEyfRCDeTgs88dR7DodFJIvQcPR+TgJudZ/KBs7vBYDmbFmdKOLHrSXDv27doJjPhCqDmgJV9qMmfz20zGG06ClSQV3AfDXIvxNDxgjwq33yUxaZfSy0Fbt9up0MqkIC2kH6auoiC3jKfn0="
