apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: POCKET_ID_ENCRYPTION_KEY
