apiVersion: v2
name: immich
version: 0.0.0
sources:
  - https://github.com/Stirling-Tools/Stirling-PDF-chart
  - https://github.com/Stirling-Tools/Stirling-PDF
dependencies:
  - name: pvc
    version: 0.0.0
    repository: file://../../charts/pvc
  - name: app-template
    version: 4.6.2
    repository: oci://ghcr.io/bjw-s-labs/helm
