pvc:
  pvcName: &pvcName stirling-pdf-data
  storageRequest: 128Mi
  moverSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000

stirling-pdf:
  image:
    registry: ghcr.io
    repository: stirling-tools/stirling-pdf
    tag: 2.14.0@sha256:a6c5e627ceef6ed323a63da13e0d44ef68503320d1917cbc7ca2fd8e4a827aae

  strategy:
    type: Recreate
  serviceAccount:
    create: false

  deployment:
    extraVolumes:
      - name: configs
        persistentVolumeClaim:
          claimName: *pvcName
    extraVolumeMounts:
      - name: configs
        mountPath: /configs

  ingress:
    enabled: true
    ingressClassName: internal
    pathType: Prefix
    hosts:
      - name: pdf.internal.neils.house
        path: /
