pvc:
  pvcName: &pvcName stirling-pdf-data
  storageRequest: 128Mi
  moverSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000

stirling-pdf:
  image:
    registry: ghcr.io
    repository: stirling-tools/stirling-pdf
    tag: 2.14.3@sha256:3b3670fce70b396ec56ba380a3cc7858e0abf83fe13f31c88f7737847763a396

  strategy:
    type: Recreate
  serviceAccount:
    create: false

  deployment:
    extraVolumes:
      - name: configs
        persistentVolumeClaim:
          claimName: *pvcName
    extraVolumeMounts:
      - name: configs
        mountPath: /configs

  ingress:
    enabled: true
    ingressClassName: internal
    pathType: Prefix
    hosts:
      - name: pdf.internal.neils.house
        path: /
