pvc:
  pvcName: &pvcName stirling-pdf-data
  storageRequest: 128Mi
  moverSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000

stirling-pdf:
  image:
    registry: ghcr.io
    repository: stirling-tools/stirling-pdf
    tag: 2.13.2@sha256:976dfa581b6cb1fb91e9b0b90284a92febe8ba6a4519e28f95c4e8e550d6d70d

  strategy:
    type: Recreate
  serviceAccount:
    create: false

  deployment:
    extraVolumes:
      - name: configs
        persistentVolumeClaim:
          claimName: *pvcName
    extraVolumeMounts:
      - name: configs
        mountPath: /configs

  ingress:
    enabled: true
    ingressClassName: internal
    pathType: Prefix
    hosts:
      - name: pdf.internal.neils.house
        path: /
