apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  nfs:
    path: /mnt/media/frigate
    server: nas.internal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: frigate-media
