apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

---
apiVersion: v1
kind: Endpoints
metadata:
  name: nextcloud
subsets:
  - addresses:
      - ip: 192.168.1.30
    ports:
      - port: 8888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
spec:
  rules:
    - host: cloud.neils.house
      http:
        paths:
          - backend:
              service:
                name: nextcloud
                port:
                  number: 8888
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - cloud.neils.house
