apiVersion: v1
kind: Service
metadata:
  name: tautulli
spec:
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181

---
apiVersion: v1
kind: Endpoints
metadata:
  name: tautulli
subsets:
  - addresses:
      - ip: 192.168.1.30
    ports:
      - port: 8181

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
spec:
  rules:
    - host: tautulli.neils.house
      http:
        paths:
          - backend:
              service:
                name: tautulli
                port:
                  number: 8181
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - tautulli.neils.house
