apiVersion: v2
name: cert-manager
version: 0.0.0
dependencies:
  - name: cert-manager
    version: v1.19.4
    repository: oci://quay.io/jetstack/charts
  - name: trust-manager
    version: v0.21.1
    repository: oci://quay.io/jetstack/charts
