apiVersion: v2
name: longhorn
version: 0.0.0
dependencies:
  - name: oauth2-proxy
    version: 0.0.0
    repository: file://../../charts/oauth2-proxy
  - name: longhorn
    version: 1.10.2
    repository: https://charts.longhorn.io
