apiVersion: v2
name: longhorn
version: 0.0.0
sources:
  - https://github.com/longhorn/charts/tree/master/charts/longhorn
  - https://github.com/longhorn/longhorn
dependencies:
  - name: oauth2-proxy
    version: 0.0.0
    repository: file://../../charts/oauth2-proxy
  - name: longhorn
    version: 1.11.2
    repository: https://charts.longhorn.io
