apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt
data:
  # Optional: Zigbee channel, changing might require re-pairing of some devices (see docs below). (Note: use a ZLL channel: 11, 15, 20, or 25 to avoid problems) (default: 11)
  ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: "25"
  # Optional: Home Assistant legacy entity attributes (default: true)
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
  # Optional: Home Assistant legacy triggers (default: true)
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "false"
  # Optional: Add a last_seen attribute to MQTT messages, contains date/time of last Zigbee message
  # possible values are: disable (default), ISO_8601, ISO_8601_local, epoch (default: disable)
  ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
  # Optional: disables the legacy api (default: true)
  ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
  # Whether to use legacy mode for the availability message payload (default: true)
  # true = online/offline
  # false = {"state":"online"} / {"state":"offline"}
  ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
  # Optional: Logging level, options: debug, info, warning, error (default: info)
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info
  # Optional: Output location of the log (default: console,file), leave empty to suppress logging (log_output: [])
  #  possible options: 'console', 'file', 'syslog'
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
  # Time after which an active device will be marked as offline in minutes (default = 10 minutes)
  ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: "10"
  # Time after which a passive device will be marked as offline in minutes (default = 1500 minutes aka 25 hours)
  ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: "1500"
  # Enable legacy integration for all devices (if applicable) (default: true)
  ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
  # Retain MQTT messages of all devices (default: false).
  ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
  # Optional: Home Assistant integration (MQTT discovery) (default: false)
  ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
  # Optional: Include device information to mqtt messages (default: false)
  ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
  # Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
  ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://emqx.emqx.svc.cluster.local:1883
  # Optional: MQTT server authentication user (default: nothing)
  ZIGBEE2MQTT_CONFIG_MQTT_USER: zigbee2mqtt
  # Optional: MQTT protocol version (default: 4), set this to 5 if you use the 'retention' device specific configuration
  ZIGBEE2MQTT_CONFIG_MQTT_VERSION: "5"
  # Optional: allow new devices to join.
  # It's important to disable permit_join after you've peered your devices.
  # This keeps the Zigbee network safe and prevents accidental joining of other Zigbee devices.
  # When a device joins, the coordinator exposes the network key.
  ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
  # Optional: adapter type, specify if you are experiencing startup problems (default: null, options: zstack, deconz, ember, zigate)
  ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ember
  # Required: location of the adapter (e.g. CC2531).
  ZIGBEE2MQTT_CONFIG_SERIAL_PORT: "{{ .Values.coordinatorPath }}"
  # Optional: RTS / CTS Hardware Flow Control for serial port (default: false)
  ZIGBEE2MQTT_CONFIG_SERIAL_RTSCTS: "true"
  # custom data directory
  ZIGBEE2MQTT_DATA: /config
