apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zigbee2mqtt
spec:
  serviceName: zigbee2mqtt
  selector:
    matchLabels:
      app: zigbee2mqtt
  replicas: 1
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "{{ .Values.nodeSelectorKey }}"
                    operator: "Exists"
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:1.40.2
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
          envFrom:
            - configMapRef:
                name: zigbee2mqtt
            - secretRef:
                name: zigbee2mqtt
          volumeMounts:
            - name: data
              mountPath: /config
            - name: coordinator
              mountPath: "{{ .Values.coordinatorPath }}"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: zigbee2mqtt-data
        - name: coordinator
          hostPath:
            path: "{{ .Values.coordinatorPath }}"
            type: CharDevice
