apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: kube-system
spec:
  secretName: wildcard-tls
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
  dnsNames:
    - "neils.house"
    - "*.neils.house"
    - "*.internal.neils.house"
