node-feature-discovery:
  worker:
    config:
      sources:
        usb:
          deviceClassWhitelist:
            # https://www.usb.org/defined-class-codes
            - "02"  # Communications and CDC Control
            - "0e"  # Video
            - "ef"  # Miscellaneous
            - "fe"  # Application Specific
            - "ff"  # Vendor Specific
