apiVersion: v2
name: grafana
version: 0.0.0
sources:
  - https://github.com/grafana-community/helm-charts/tree/main/charts/grafana
dependencies:
  - name: pvc
    version: 0.0.0
    repository: file://../../charts/pvc
  - name: grafana
    version: 12.3.0
    repository: oci://ghcr.io/grafana-community/helm-charts
