pvc:
  pvcName: grafana-data
  storageRequest: 512Mi
  moverSecurityContext:
    runAsUser: 472
    runAsGroup: 472

grafana:
  env:
    GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
  ingress:
    enabled: true
    ingressClassName: external
    hosts:
      - grafana.neils.house
  persistence:
    enabled: true
    existingClaim: grafana-data
  deploymentStrategy:
    type: Recreate
  grafana.ini:
    server:
      root_url: https://grafana.neils.house
    auth:
      disable_login_form: true
