apiVersion: v1
kind: Service
metadata:
  name: zwave-js-ui
spec:
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
      name: web-ui
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: websocket
  selector:
    app: zwave-js-ui
