loki:
  global:
    priorityClassName: system-node-critical
  deploymentMode: SingleBinary
  loki:
    annotations:
      secret.reloader.stakater.com/reload: "loki"
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    compactor:
      retention_enabled: true
      delete_request_store: "s3"
    limits_config:
      max_query_lookback: 730h
      retention_period: 730h
    schemaConfig:
      configs:
        - from: "1970-01-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage:
      type: "s3"
      s3:
        endpoint: "http://nas.internal:30188"
        region: "garage"
        accessKeyId: "${AWS_ACCESS_KEY_ID}"
        secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
        s3ForcePathStyle: true
      bucketNames:
        chunks: "loki"
        ruler: "loki"
        admin: "loki"
  singleBinary:
    replicas: 1
    extraArgs:
      - '-config.expand-env=true'
    extraEnvFrom:
      - secretRef:
          name: loki
  gateway:
    replicas: 0
  write:
    replicas: 0
  read:
    replicas: 0
  backend:
    replicas: 0
  test:
    enabled: false
  chunksCache:
    enabled: false
  resultsCache:
    enabled: false
