apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: k8s-upgrade
spec:
  kubernetes:
    # renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker
    version: v1.35.2
  healthChecks:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      expr: status.conditions.filter(c, c.type == "Synchronizing").all(c, c.status == "False")
    - apiVersion: longhorn.io/v1beta2
      kind: Volume
      expr: status.state != "attached" || status.robustness == "healthy"
