apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  replicas: 1
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          image: lscr.io/linuxserver/radarr:5.7.0
          ports:
            - containerPort: 7878
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: data
              mountPath: /config
            - name: downloads
              mountPath: /mnt/tank/Downloads
            - name: movies
              mountPath: /mnt/tank/Movies
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: radarr
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-pvc
        - name: movies
          persistentVolumeClaim:
            claimName: movies-pvc
