app-template:
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
  controllers:
    unpackerr:
      annotations:
        reloader.stakater.com/auto: "true"
      containers:
        unpackerr:
          image:
            repository: ghcr.io/unpackerr/unpackerr
            tag: 0.15.0@sha256:9f4cb99b78d8fe2d55f79c490a715e14a8a28d9868373dad642ca5adc2ac3e91
          env:
            TZ: "America/Los_Angeles"
            UN_RADARR_0_URL: http://radarr.radarr.svc.cluster.local:7878
            UN_SONARR_0_URL: http://sonarr.sonarr.svc.cluster.local:8989
            UN_WEBSERVER_LOG_FILE: /logs/unpackerr.log
          envFrom:
            - secretRef:
                name: unpackerr
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
  persistence:
    downloads:
      type: nfs
      server: nas.internal
      path: /mnt/media/downloads
      globalMounts:
        - path: /mnt/media/downloads
    logs:
      type: emptyDir
