pvc:
  pvcName: emqx-data
  storageRequest: 1Gi
emqx:
  replicaCount: 1
  ingress:
    dashboard:
      enabled: true
      hosts:
        - emqx.internal.neils.house
      ingressClassName: internal
  persistence:
    enabled: true
    existingClaim: emqx-data
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/controller
                operator: In
                values:
                  - home-assistant
          topologyKey: kubernetes.io/hostname
