apiVersion: v1
kind: ConfigMap
metadata:
  name: sabnzbd-config
data:
  DEBUG: "false"
  PUID: "1000"
  PGID: "1000"
  UMASK: "000"
  VPN_ENABLED: "yes"
  VPN_PROV: "pia"
  VPN_CLIENT: "wireguard"
  LAN_NETWORK: "192.168.1.0/24"
  NAME_SERVERS: "1.1.1.1,1.0.0.1"
