apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-downloads
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  nfs:
    path: /mnt/media/downloads
    server: nas.internal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: sabnzbd-downloads
