apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: VPN_USER
      remoteRef:
        key: PIA_VPN_USER
    - secretKey: VPN_PASS
      remoteRef:
        key: PIA_VPN_PASS
