apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
value: cifs://c-smb.local/longhorn_backups

---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target-credential-secret
value: cifs-credentials
