# this should be unique across all PVCs in the cluster
pvcName: name

# set to true when creating a new PVC
initial: false

accessModes:
  - ReadWriteOnce

storageRequest: 1Gi
storageClassName: longhorn

volumeSnapshotClassName: longhorn

cacheCapacity: 1Gi
cacheStorageClassName: longhorn-ephemeral
cacheAccessModes:
  - ReadWriteOnce

resticBucket: s3:http://minio.minio.svc.cluster.local:9000/volsync

moverSecurityContext: {}
  # runAsUser: 568
  # runAsGroup: 568
  # fsGroup: 568

snapshotRetention:
  hourly: 24
  daily: 7
  weekly: 5
