apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: nextcloud
spec:
  encryptedData:
    password: "AgBafi2giV4pQKQuTRA88mSMB1V4qaLRk0tk97jhMvcsDChCzDQQt2onJJpnbsgipm+3gk72R8SUngDXftYwCVPkP/Zwafu881pSytPAJs9QMdOxtKpxHciJuhYCnavkjA0MvST0yAxtdGlrs7A4+LDMtGf7LYq7i4RZEVLBwlMik0J2/XI0uKXTvrzQAqiyYLHKTQHO581EUmf8H93GdeSkgA+P5AZyj+V8C05lVI/47J1WCt9Gn8jyjAER5JZXDdERGN9K7E/uFq4rT+TEdaLpPnc0cAsJ0IC2rPJWgpDoLWHyA39fAh1bhbOPApzQp783rlCVJrQOFkwpbzUCqyaVoiMgBsRO5Rf5FstRNJXAZzlSXgFFic9l3cBBEvOd9TCT8Zf6pKbZUlMCAC06YNlTqwviYYyO1OwLCKdP3GwB6QehwwE6VUiX4YeHXM5AuUJuB78uoMDKzgkwihywxPF8yNIfyJOnkeFo1WWbXIH9KjBjxOVdBawmRzMJtGuDfYZH/z+b41DFFy6GMT1k4G5Vzi4iaGuKXBm6XQ0D641daawoE5WsOQNn814p4dgkqIvsBZx3CTSYfT+V3akrHmJx5MGBab++9KgucesipTKksNV4BxpgMYhro3isHXHH2Jyy9QZppCO1pY92uo+aJluL9aSOZggHrDQQ7Y3hp5qwz2MMW0Fv7KWLmXOYzbLV4ndG7tG3ZwRX5/7Evf9FZ72XpYK/kg=="
