apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pgdata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 16Gi
  volumeName: pvc-7a0eaf03-e4c0-4fc6-9933-a6a1e743bbce
