apiVersion: batch/v1
kind: CronJob
metadata:
  name: exporter
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: exporter
              image: ghcr.io/paperless-ngx/paperless-ngx:2.20.0@sha256:8ffd737c69a569bbdadc118e7f54b0b1050ffac2868fdf9e390a68cb7c82a79d
              imagePullPolicy: IfNotPresent
              args:
                - document_exporter
                - /usr/src/paperless/export
                - --delete
              envFrom:
                - configMapRef:
                    name: paperless-ngx
                - secretRef:
                    name: paperless-ngx
              volumeMounts:
                - name: data
                  mountPath: /usr/src/paperless/data
                - name: media
                  mountPath: /usr/src/paperless/media
                - name: exports
                  mountPath: /usr/src/paperless/export
          restartPolicy: OnFailure
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: paperless-data
            - name: media
              persistentVolumeClaim:
                claimName: paperless-media
            - name: exports
              nfs:
                path: /mnt/data/paperless_exports
                server: nas.internal
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - webserver
                  topologyKey: kubernetes.io/hostname
