apiVersion: batch/v1
kind: CronJob
metadata:
  name: exporter
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: ghcr.io/paperless-ngx/paperless-ngx:2.10.2
              imagePullPolicy: IfNotPresent
              command:
                - document_exporter
                - /usr/src/paperless/export
                - --delete
              env:
                - name: PAPERLESS_DBPASS
                  valueFrom:
                    secretKeyRef:
                      name: paperless-db-credentials
                      key: POSTGRES_PASSWORD
              envFrom:
                - configMapRef:
                    name: paperless
                - secretRef:
                    name: paperless
              volumeMounts:
                - name: data
                  mountPath: /usr/src/paperless/data
                - name: media
                  mountPath: /usr/src/paperless/media
                - name: exports
                  mountPath: /usr/src/paperless/export
          restartPolicy: OnFailure
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: paperless-data
            - name: media
              persistentVolumeClaim:
                claimName: paperless-media
            - name: exports
              persistentVolumeClaim:
                claimName: paperless-exports
