apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotenberg
spec:
  selector:
    matchLabels:
      app: gotenberg
  replicas: 1
  template:
    metadata:
      labels:
        app: gotenberg
    spec:
      containers:
        - name: gotenberg
          image: docker.io/gotenberg/gotenberg:8.17.2
          ports:
            - containerPort: 3000

          # The gotenberg chromium route is used to convert .eml files. We do not
          # want to allow external content like tracking pixels or even javascript.
          command:
            - "gotenberg"
            - "--chromium-disable-javascript=true"
            - "--chromium-allow-list=file:///tmp/.*"

---
apiVersion: v1
kind: Service
metadata:
  name: gotenberg
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: gotenberg
