apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-exports
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  nfs:
    path: /mnt/data/paperless_exports
    server: nas.internal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-exports
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: paperless-exports

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-inbox
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  nfs:
    path: /mnt/data/paperless_inbox
    server: nas.internal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-inbox
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: paperless-inbox
