apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.pvcName }}-volsync-b2
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    # be careful mixing helm and sealedsecrets templates here
    # to escape the double curlies, use {{ "{{" }} and {{ "}}" }}
    # https://github.com/helm/helm/issues/2798#issuecomment-326454957
    data:
      RESTIC_REPOSITORY: s3:{{ "{{" }} .bucket {{ "}}" }}/{{ .Values.pvcName }}
  encryptedData:
    bucket: AgCX3+VKV5Yviv+t8Alwmyk2KoBuJyxt/R5iCXV/aKQ84CCoTXA5dKhhU3CQopJK2d4wOtS5gcWsukeYDCUxFtS17RM/XW1L0VLvmVMbCZQ3y8QIomTHi1znFrF+j9zSnGAyFGnzzm0wWNIBkfdylK+yzrEO6qeMPcaUhvp+PXOAKaCK1aX1PvKRc4HKqvKDVf9rSGVbVKK7Sg7QFJegDZ5uoD2mE+C4Wzv5kTj9vhFv636ktZ2OvyWcSTbfGkFelvRJbc9EXjm7NDKAt2aWQXATHDno3mEEOKTJ6ktI2RGGX4N4MaXdpbFLhK057txcyyzQL/n2gdcwSexRsZwGrX306IbZxDxN7jRJqZYmFJb3BBTgtw+oUjjpFoZqXJb1ePAUDtDNFVc1Y+B0DDin9enOmIWbMCz7UZfstMYGzps3VtNEMouZOgzfPReys+svsWDsJp6qBigtR+bx3fj3Lc4d/2wmf1ekv1aKHKdoO5eZ6If1UB6DGje3pCoWaGwr4IdwD/bJXs1MxwyrP1tyT4Uiv6JDDlGUyulNoA6HWcCv8uFBP6DtxqAMhjMpbRWFjpvs0OYiQfXU2nJrc5f/lEIJQhZPQoWCRASlrmf5ojdU8C3Wz7lfXmHCN1Kll0QiMQ8r5SZkMkEXSm93PlIjFBI7UqV2eVgLNGr8KT51zkUnEK/H/IgYiDqrdp1NkOO6+LxBXvqsHKgK/0vaQA31DBe37XdoENpoVhq+I+/q4hqAN6ytXvhWTq7QDZb8dtoxaBK98jufX6PDbRaQFj0=
    RESTIC_PASSWORD: AgCr7U35cRaP6Xypj/UbA63+PwkCIAGpOsBYIEuTkd/Tvqk24+7Lwq6j/pvRvejctzmuo30ZIt6m2+g9Jbkmd6j8GS4WF/5AJ68s28DCFequzlfFDiEvayk3tF1rP9FkxSVOoEyuMhpiv3o/n0UayTcvuelFlhXRFS/HvIrqaurGY7fBmrEIof3tDpLkin6xieDRCUH93gm71TscSNR30OFyE2L/YjWAv9AEt5cPpm2NWiiXHrcn67fN87oUrefdK+rGuNUpx0vaIBwFR21C5B5IsuYvo+KwuvJjgUPTSdJiOvnaodrh6HnLs+BowIevEKGVvXmq4romLZIH6TU5z12QuQED8f96al4/blS3G789BbUeFtCJ5t0c2ZldRbuqlQUbCFPjRl6fBy3b9RtX0L3VIgXxtiBi0SDSAtLHKR1OgOqK7434PwJoligTozBaPoT0QtZUa+bqzgSlVJztyNJQgrrne0bam+Vo8108NOM7IZ6MzAWY2YeVd2iWbzh1y4rI1Hh5PfJ9LdO+wjpmG7aKOwlrwxle9rg1DlfUgA3bmZ3qA/QvUfplG8rgFMoHNRcSFDgZYMkUThDO+elbm/U2ClPvyMCjeBAw1OCShRujFEoJ2nyEkAIu7NDlSIBKZgCly1N974BK6SEpiWoRrP+Eg8yHVgW9CqCsAsYnCt73Q4B4Gw87j22CmVZum1rGEcz60FXkx0gcLhI8OVF953C2Lax2qA==
    AWS_ACCESS_KEY_ID: AgBW/+nZksSX0FgTM85yf4MWouN4WEYCMuGiTv0J7G6MTwr263IIPkIQlWqznR3H4pIAniQ6OImVbnP7xHGF2s4l0VS753Ygzq8m2G8HN8aY4KVGOoinsNlQWHPOikDgcHGushK9301LYBoFM6fGGnQ+C2TMJLfQdp6PAvEC8+MVTy6nQhZBAQPB2SLAULWIftqRf6qlr22U4P7XZR7FI8Y5pnl/ZDQk85GPgvB/FitPPMxHz54aXKhtEb/Dqdbk5DqyJiz5nLKVDh9mTGvDCdAEGRZ39SkzX2H5FXM5xnZvJoN26WnvRJxpKE0k005b2GOpy25c6a0Sr5uk/r7NGB9YspEsOBxClA3crGHk1QGbPM2iT+tXxODCDqruXRKZv0QYPXioNzbAOdhoPRsDwLm7HaCCa26OURZ5RzxiGq1i/cQEUhNQv2pPThfdDRjyTYVOnJnI6xjWVqlFkQ9S4tVSDQXajmxuA30FfZUHgJ6t9rdsATwS2bH+6ZyzOI9/jcoqvGpzRLHn/JTs2p5VWaKrXNP2WRCz0NIlHWsX0ZSdq+Vo2zUHWPvlJliaq1ffYEG9S8x9flHUNswCKuSFAai072Nb9wY4cTDXONavB4Y7fhQWta0TW+XIRn3rPGsjpiX6sgEEMYfH9uveoYeskiJbXQ11o2bB2dXtUnWZ3LAS+km8gxOlCNYkDi4A4reiE3x58xo7qYW+R9zHRAjqJ3fesUAyTvNl3TIs
    AWS_SECRET_ACCESS_KEY: AgAfx4WsieykYSweqfmEV/enpkoRsVt8Es8BTNIf/hNZEnYo4pNKMTdJqBZinRP51vMxKbPF0oReOd/YEiAOgECDEH4Pac7vH0d0wJS5OHWhZ4MmjdDh7xsngp4w2RNfJj+IqNW87BBIYMCpf5bls/JEKTyaOvvy9DnPHgoldHrWC2SDWR1gYsyG75YUCvxm8620dQ336UmDIUxrQY9NZKrAUpqKUSDsHwGm9roUJFU8Gfsx//xRI90BM53Yk1eKIw8uEXBC13hvv6qGzVZEQKFLwOfahkDFHfy4sKGPMYsgT4YB87JH1lZnjB6Gw8ULF1DzNhfhUTio6IiGZcHyhcDQkO8ytB5+GtYJKvEJUewKK0rJ9BQH35wl8y3togpfbkG7oyE2fuql0diK6Baa5zGAUF+EXGJ1yEoLBp89hTnDELfRxKWcMvVqYGu00JuGg63lD6bEzfs1OOpOZWY5i5p1F1deO8HObJCXADACmzNOux/5oHSSyfet9y3fQRhmtoJN/od+7ecw+VbJIapC541owuRtLac58y5O9+hInOWZuyceAkvITfL9CnjNVqM63UjNPJgNfDssJRDelIAhQQw1ekwaGyMVx2Q4Zw/qPG3AqeLBgAnxixewmIljqknZyG5+24luLRHmVL1n/2AGW/+fm7/Pp/hw7dfJj8sGh84qyiECKmJ2ajMEyFfFefhQbB67PUP9yaC2mmvcYTuMsA4xqDmjp76XR33lmbkQ3cyi

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: {{ .Values.pvcName }}-volsync-b2-src
spec:
  sourcePVC: {{ .Values.pvcName }}
  trigger:
    # daily at 12:00 utc
    schedule: "0 12 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: "{{ .Values.pvcName }}-volsync-b2"
    volumeSnapshotClassName: {{ .Values.volumeSnapshotClassName }}
    cacheCapacity: {{ .Values.cacheCapacity }}
    cacheStorageClassName: {{ .Values.cacheStorageClassName }}
    cacheAccessModes: {{ .Values.cacheAccessModes }}
    storageClassName: {{ .Values.replicationStorageClassName }}
    accessModes: {{ .Values.accessModes }}
    moverSecurityContext: {{ .Values.moverSecurityContext | toYaml | nindent 6 }}
    retain: {{ .Values.snapshotRetention | toYaml | nindent 6 }}
