apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.pvcName }}-volsync-minio
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    # be careful mixing helm and sealedsecrets templates here
    # to escape the double curlies, use {{ "{{" }} and {{ "}}" }}
    # https://github.com/helm/helm/issues/2798#issuecomment-326454957
    data:
      RESTIC_REPOSITORY: s3:http://nas.internal:30188/volsync/{{ .Values.pvcName }}
  encryptedData:
    RESTIC_PASSWORD: AgCSLZFOxVa4obmxH6zRcwu5fESnx6jTaim+lZUZQcfN1L5qUhy4iEDU5upeZHx9NExPnmHk+dB0eNKR0kunm4jIZqF9rA1zCyBHcoX8Ih7BBQaZkbwk8hhnFdVsdXqIHo/U66v746+DbW2Sv+OgDM3wh1BrTHMO5EsTJNGffT/mBVF1eRoDbrzzeyqLGxj5yNqIZAiZ7+wPR30KXHw/cXXfGJpN+keIFQ+z+YI0/AprFdpRF/XN+g8X22mLAceHiQBITg8BgOYmU6PUFcltKtPqa037bS7cl7cB5oANCX2t9Q+LyivyTw2rnYyTifd6y79dLA0h1BNwZs1nGXaBzVvECgELV/hBatPxomNljeBwWQmOLqvfG9dypYNJlOAX0VhkmdfhsSiP1mG6DSG9Z1WREqUae9DI9Sbo2FDTHZjpDHCxhi+XMo/TvQeEzNuoaEF+vksVp4TCfqEcZ+GtG8seoqj++Vavoqt7Ud3wBGtkyF7+BLoRwikqF+TUEaIWjJatu4uknjkqYY4d/fLC9Q+mEXvtlKvKb7mF7XW+tW2hlvtq+Z/TfJJJElux94QRM3syGE4JsxGzinCY9NnfquBki3std4DX9aeIx9yLxmUxB8frbranOhIms8OyBYKz7SpP+ibn0lDUf2uGVqIe5ZGfsXWCSQmqN1QuTbtGbVYZODa+pLMxYz4st5Pb7b5sA4Il+W8wTX5rgzkQPh+7Zcn38woy4g==
    AWS_ACCESS_KEY_ID: AgDBtMOQKq10fTNKAMqXHUl/IYJwowTWuvLwgtXISWQDkpk/FKCVZLZERyhjmBUlybOxr4wy6J0e0YJ1aKE/TbG9VIdnSuBP5I5BYN3/wyTtDSiutNvvJEax9ogQIUD2CVWEl+A16aIFs0pPzE3c1oabn2lqF95gBkHn2cmEzNczquAgKZGuHKAtxjenhIsEE0+ixVT7jCV6PFpKNjDIKBM9nHtxRxxvv0i7ukT3+HF1VzwjfcGt7v8nVZ/obzqanwHvetCTNMa1GufGcT4Q/hdnzYavbqUehrL9Ed8zG78DfzO6HjIoppEDgRrgCZDY5NiSg2d1pGBXKzvmSYq5P5KAYAyKIYR9bQRiuW9CKdWSXqRi02x0qDzmD3RSa5yw7gu4BsT7ZX8pH5qX72TpRH7uXnKEgbZeZdL+hivnhM5RFPzVhLg7ebhZ6CyuFXk4+9ufFC2NrYeUYOJYbqbezqbkqphYeJEngF/ozbgXa2amIV7c+Joq7Zzm96z4BQAxAbJZN9bscUzF6IctGhB/1BV3CeclX+HOCCBPYjpItpoChIrwJD2MnGyvFjcKlgNQs8BjeSxqC8T/IvbDX+odA3fsWzn40I1VHuRvGwvYbEaHw53+1j0TDvTb4elvTIAzazYBDOIuxVMNBXOLgd2UnKttBqZaONX+Ku6ZJBokCBHSCQxUg5IEWw9b9j9Q5YxUEtiCfEOqU/ZSkWB2DFVJ7GChEGcGi4b9dqCSAA==
    AWS_SECRET_ACCESS_KEY: AgCMzMxGiuAR30sobiX5rsHf8gTA4OYYzv3hhKVeWoPyjPsNsnSPuj0rPpL2yNg2lsjzjK4takYCi44l+RFU/bbwO+YZPruKE9TBx0jux91q0RTCIjNhPpvkZZn+dVx6BJjHakN1g4n6PF46tL0y6mw8ITdcKTJYkEicpMQqPidQvd40qZZV1L07+I+JmPOrCRldoTRL1fhswqcOiGEg3jLueEp/cI0V+zd7/1WS6dDbABvYPO1TpJxuqdJM0zhlCURzf5Dn3fjAXNDV1wj2YiT6jQAh31tpIpee7Yb8Da9hRcIMJwaiobQX62db92yl9lS4l2Pki0tAH/E39w75s5NQ1LdlsODqmQMdd/8gWlrqGdP+t3rMI0aJZaDuIzNLZojl6ch6Bqxvew+DbwNOGAx+pU+zeVAtBWFXKHQqvbnBTHpNVJK5XcpC8/i2p+VNqn+CYUHm7DpUUBYVVEvchGnHnMh0UahZTys/YktMtV6hxvra80AVZspnyr1vgmbMJLFtuhzrTIhMbXkdEiL9xzeyErCGcBsuyyXi3WjGQGBl/U877VKHOW9bsGr2M4+gyWB7xZUUh+02hv7AVS/gBlsuCALyymLS8H0IuK1tjuiGhuLap5us0FXW8oypt5KZQgrLQOCkgjlCqxYpsoygYiZgY77VMe8iKWIt1w/lnR8UXOFRjCONrRtcIjgVMLFHzBQULxGeYkAZtTzNlXSXK7K/GGvz/RzHzOw1kNaPZtluTRgxAZjlutFF+AUU3eQIGV5a3nn+N0hdjURmOkzuiXBO

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: {{ .Values.pvcName }}-volsync-minio-src
spec:
  sourcePVC: {{ .Values.pvcName }}
  trigger:
    schedule: {{ if eq .Values.triggerSchedule.minio "random" -}}
        {{- $triggerMinute := mod (randNumeric 2 | int64) 60 -}}
        {{- $triggerHour := mod (randNumeric 2 | int64) 24 -}}
        "{{ $triggerMinute }} {{ $triggerHour }} * * *"
      {{- else -}}
        {{ .Values.triggerSchedule.minio | quote }}
      {{- end }}
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: "{{ .Values.pvcName }}-volsync-minio"
    volumeSnapshotClassName: {{ .Values.volumeSnapshotClassName }}
    cacheCapacity: {{ .Values.cacheCapacity }}
    cacheStorageClassName: {{ .Values.cacheStorageClassName }}
    cacheAccessModes: {{ .Values.cacheAccessModes }}
    storageClassName: {{ .Values.replicationStorageClassName }}
    accessModes: {{ .Values.accessModes }}
    moverSecurityContext: {{ .Values.moverSecurityContext | toYaml | nindent 6 }}
    retain: {{ .Values.snapshotRetention | toYaml | nindent 6 }}

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: {{ .Values.pvcName }}-volsync-minio-dest
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "{{ .Values.pvcName }}-volsync-minio"
    copyMethod: Snapshot # must be Snapshot
    volumeSnapshotClassName: {{ .Values.volumeSnapshotClassName }}
    cacheCapacity: {{ .Values.cacheCapacity }}
    cacheStorageClassName: {{ .Values.cacheStorageClassName }}
    cacheAccessModes: {{ .Values.cacheAccessModes }}
    storageClassName: {{ .Values.replicationStorageClassName }}
    accessModes: {{ .Values.accessModes }}
    capacity: {{ .Values.storageRequest }}
    moverSecurityContext: {{ .Values.moverSecurityContext | toYaml | nindent 6 }}
    cleanupCachePVC: true
    # cleanupTempPVC: true
