apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.pvcName }}-repository
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    # be careful mixing helm and sealedsecrets templates here
    # to escape the double curlies, use {{ "{{" }} and {{ "}}" }}
    # https://github.com/helm/helm/issues/2798#issuecomment-326454957
    data:
      RESTIC_REPOSITORY: s3:http://minio.minio.svc.cluster.local:9000/volsync/{{ .Values.pvcName }}
      AWS_ACCESS_KEY_ID: notvolsync
  encryptedData:
    RESTIC_PASSWORD: AgCr7U35cRaP6Xypj/UbA63+PwkCIAGpOsBYIEuTkd/Tvqk24+7Lwq6j/pvRvejctzmuo30ZIt6m2+g9Jbkmd6j8GS4WF/5AJ68s28DCFequzlfFDiEvayk3tF1rP9FkxSVOoEyuMhpiv3o/n0UayTcvuelFlhXRFS/HvIrqaurGY7fBmrEIof3tDpLkin6xieDRCUH93gm71TscSNR30OFyE2L/YjWAv9AEt5cPpm2NWiiXHrcn67fN87oUrefdK+rGuNUpx0vaIBwFR21C5B5IsuYvo+KwuvJjgUPTSdJiOvnaodrh6HnLs+BowIevEKGVvXmq4romLZIH6TU5z12QuQED8f96al4/blS3G789BbUeFtCJ5t0c2ZldRbuqlQUbCFPjRl6fBy3b9RtX0L3VIgXxtiBi0SDSAtLHKR1OgOqK7434PwJoligTozBaPoT0QtZUa+bqzgSlVJztyNJQgrrne0bam+Vo8108NOM7IZ6MzAWY2YeVd2iWbzh1y4rI1Hh5PfJ9LdO+wjpmG7aKOwlrwxle9rg1DlfUgA3bmZ3qA/QvUfplG8rgFMoHNRcSFDgZYMkUThDO+elbm/U2ClPvyMCjeBAw1OCShRujFEoJ2nyEkAIu7NDlSIBKZgCly1N974BK6SEpiWoRrP+Eg8yHVgW9CqCsAsYnCt73Q4B4Gw87j22CmVZum1rGEcz60FXkx0gcLhI8OVF953C2Lax2qA==
    AWS_SECRET_ACCESS_KEY: AgAMWoG/XRO0Qj05YOtTI+d5BYPaaTzRh1eXhTE2UMnp5XMYvunRG72PbygnJ8gT/s06FZQkmeDAjjfeCAKZtGIYOt2/EmpDHLdps0XY4g//E8svDBer4xpgYMrlVkQBLdzw1dF7v3ukc2e0oVBNLAi7KJ2+lDgGdEhVdjuniJTr0obVJbpOtJbY20HNG+xZLmMqRziePgdhMVypdi1E1soNdEmaJhTPyY9rNUsQTpetg36OeAIi8TGTyAcvo8mOf8CBq4YhI0kv+lW4KXal+ejc+mZSWe6Ao6Q6PkrqhxER6X6efeSFi7YfWbTRDmjCFEQwDM7/CUmdzwWEkSfHsM16Rv3HJNxpfw3EHRpL04XfJMWlWI6xdNQaaTK/tqcZ+Bu7o6BNMmVwfU02FIOeoncouDCiCC/JJWv1/EWUaAWSHDIVG1RB8HlYEmNs3pybEyqGkxp50r/Og9kZCgn4EUh2t7AfxkgOMzCc7Dt8Qf3oQJyIyUMRWGAvBCy1+YfqMOI0D9tcrhVrV8Qf/t0JUR714uUL5gQtFdY090lVssqEcm8XSC+XYoy82f7s5PLQzsgfaEiZIdyOi/vMIC6/FEseOIOB9WwER3Z3s9tp0XfzQfzwr8Ll53ciKxJksT2PEURtIC2n3VMg7Hlu6zfWqes/NQFkW2Linw4OqqPHvtGm/wcXNzgY5DdKguHNcbPIlyhIVTFQpJQE4uecrDLEsEyBMd4zrg==
