apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  selector:
    matchLabels:
      app: sabnzbd
  replicas: 1
  template:
    metadata:
      labels:
        app: sabnzbd
    spec:
      containers:
        - name: sabnzbd
          image: binhex/arch-sabnzbdvpn:4.3.2-1-06
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: pia-credentials
          env:
            - name: DEBUG
              value: "false"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "000"
            - name: VPN_ENABLED
              value: "yes"
            - name: VPN_PROV
              value: "pia"
            - name: VPN_CLIENT
              value: "wireguard"
            - name: LAN_NETWORK
              value: "192.168.1.0/24"
            - name: NAME_SERVERS
              value: "1.1.1.1,1.0.0.1"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true # required for wireguard
          volumeMounts:
            - name: data
              mountPath: /config
            - name: downloads
              mountPath: /mnt/tank/Downloads
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sabnzbd
        - name: downloads
          persistentVolumeClaim:
            claimName: downloads-pvc
