apiVersion: v1
kind: ConfigMap
metadata:
  name: radicale
data:
  config: |
    [server]
    hosts = 0.0.0.0:5232

    [auth]
    type = htpasswd
    htpasswd_filename = /config/users
    htpasswd_encryption = bcrypt

    [storage]
    filesystem_folder = /data/collections
