apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radicale
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: users
      remoteRef:
        key: RADICALE_AUTH_DB
