ingress-nginx:
  controller:
    kind: DaemonSet
    ingressClassResource:
      name: internal
      default: true
      controllerValue: k8s.io/ingress-nginx-internal
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        metallb.io/loadBalancerIPs: 192.168.1.27
    extraArgs:
      default-ssl-certificate: ingress-nginx-internal/wildcard-tls
    config:
      force-ssl-redirect: true
      proxy-body-size: 0
      proxy-read-timeout: 3600
      proxy-send-timeout: 3600
      worker-shutdown-timeout: 60s
    metrics:
      enabled: true
    podAnnotations:
      prometheus.io/port: "10254"
      prometheus.io/scrape: "true"
