apiVersion: v1
kind: ConfigMap
metadata:
  name: privoxy-config
data:
  DEBUG: "false"
  PUID: "1000"
  PGID: "1000"
  UMASK: "000"
  ENABLE_PRIVOXY: "yes"
  VPN_ENABLED: "yes"
  VPN_PROV: "pia"
  VPN_CLIENT: "wireguard"
  LAN_NETWORK: "192.168.1.0/24,10.244.0.0/16"
  NAME_SERVERS: "1.1.1.1,1.0.0.1"
