apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
spec:
  serviceName: prowlarr
  selector:
    matchLabels:
      app: prowlarr
  replicas: 1
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:1.20.1
          ports:
            - containerPort: 9696
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
          volumeMounts:
            - name: prowlarr-data
              mountPath: /config
        - name: privoxy
          image: binhex/arch-privoxyvpn:3.0.34-2-05
          ports:
            - containerPort: 8118
          envFrom:
            - secretRef:
                name: prowlarr-vpn-credentials
            - configMapRef:
                name: privoxy-config
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true # required for wireguard
          volumeMounts:
            - name: privoxy-data
              mountPath: /config
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - curl --fail --proxy http://localhost:8118 https://jsonip.com || exit 1
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20
      volumes:
        - name: prowlarr-data
          persistentVolumeClaim:
            claimName: prowlarr-data
        - name: privoxy-data
          persistentVolumeClaim:
            claimName: prowlarr-privoxydata
