apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
spec:
  serviceName: prowlarr
  selector:
    matchLabels:
      app: prowlarr
  replicas: 0
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:1.20.1
          ports:
            - containerPort: 9696
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
          volumeMounts:
            - name: prowlarr-data
              mountPath: /config
      volumes:
        - name: prowlarr-data
          persistentVolumeClaim:
            claimName: prowlarr-data
