apiVersion: v2
name: plex
version: 0.0.0
dependencies:
  - name: pvc
    version: 0.0.0
    repository: file://../../charts/pvc
  - name: app-template
    version: 4.3.0
    repository: https://bjw-s-labs.github.io/helm-charts
