pvc:
  pvcName: seerr-data
  storageRequest: 128Mi

global:
  createDefaultServiceAccount: false

app-template:
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
  controllers:
    seerr:
      containers:
        seerr:
          image:
            repository: ghcr.io/seerr-team/seerr
            tag: v3.4.1@sha256:f4768de5f616248d723e05891f3345a1402123775d03bf0890dbfedc0831bda1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
  service:
    seerr:
      controller: seerr
      ports:
        http:
          port: 5055
  ingress:
    seerr:
      className: external
      hosts:
        - host: requests.neils.house
          paths:
            - path: /
              service:
                identifier: seerr
                port: http
  persistence:
    config:
      existingClaim: seerr-data
      globalMounts:
        - path: /app/config
