pvc:
  pvcName: seerr-data
  storageRequest: 128Mi

app-template:
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
  controllers:
    seerr:
      containers:
        seerr:
          image:
            repository: ghcr.io/seerr-team/seerr
            tag: v3.2.0@sha256:c4cbd5121236ac2f70a843a0b920b68a27976be57917555f1c45b08a1e6b2aad
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
  service:
    seerr:
      controller: seerr
      ports:
        http:
          port: 5055
  ingress:
    seerr:
      className: external
      hosts:
        - host: requests.neils.house
          paths:
            - path: /
              service:
                identifier: seerr
                port: http
  persistence:
    config:
      existingClaim: seerr-data
      globalMounts:
        - path: /app/config
