apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unpackerr
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: UN_RADARR_0_API_KEY
      remoteRef:
        key: RADARR_API_KEY
    - secretKey: UN_SONARR_0_API_KEY
      remoteRef:
        key: SONARR_API_KEY
