pvc:
  pvcName: frigate-data
  storageRequest: 1Gi
  moverSecurityContext:
    runAsUser: 2000
    runAsGroup: 2000
    fsGroup: 2000

frigate:
  config: |
    tls:
      enabled: false
    mqtt:
      enabled: False
    ffmpeg:
      hwaccel_args: preset-vaapi
    detectors:
      ov:
        type: openvino
        device: GPU
    model:
      width: 300
      height: 300
      input_tensor: nhwc
      input_pixel_format: bgr
      path: /openvino-model/ssdlite_mobilenet_v2.xml
      labelmap_path: /openvino-model/coco_91cl_bkgr.txt
    record:
      enabled: True
      retain:
        days: 3
        mode: all
      events:
        retain:
          default: 30
          mode: motion
    go2rtc:
      streams:
        doorbell:
          - rtspx://192.168.1.2:7441/GVrnERomoLBhSweV
          - "ffmpeg:doorbell#audio=opus"
        doorbell_low:
          - rtspx://192.168.1.2:7441/War6N7XcwG5qZQPA
        lanes_room:
          - rtspx://192.168.1.2:7441/IhNLgvvnMANAjUQM
          - "ffmpeg:lanes_room#audio=opus"
        lanes_room_low:
          - rtspx://192.168.1.2:7441/iaCJB4k8UCy6g9cw
        lolas_room:
          - rtspx://192.168.1.2:7441/hDL4Xu0TOO5ZX5Xs
          - "ffmpeg:lolas_room#audio=opus"
        lolas_room_low:
          - rtspx://192.168.1.2:7441/G30iIHsKMJFeVCdu
    cameras:
      doorbell:
        enabled: True
        ffmpeg:
          output_args:
            record: preset-record-ubiquiti
          inputs:
            - path: rtsp://127.0.0.1:8554/doorbell
              input_args: preset-rtsp-restream
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/doorbell_low
              input_args: preset-rtsp-restream
              roles:
                - detect
      lanes_room:
        enabled: True
        ffmpeg:
          output_args:
            record: preset-record-ubiquiti
          inputs:
            - path: rtsp://127.0.0.1:8554/lanes_room
              input_args: preset-rtsp-restream
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/lanes_room_low
              input_args: preset-rtsp-restream
              roles:
                - detect
      lolas_room:
        enabled: True
        ffmpeg:
          output_args:
            record: preset-record-ubiquiti
          inputs:
            - path: rtsp://127.0.0.1:8554/lolas_room
              input_args: preset-rtsp-restream
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/lolas_room_low
              input_args: preset-rtsp-restream
              roles:
                - detect
  ingress:
    enabled: true
    ingressClassName: internal
    hosts:
      - host: frigate.internal.neils.house
        paths:
          - path: /
            portName: http-auth
  persistence:
    config:
      enabled: true
      existingClaim: frigate-data
    media:
      enabled: true
      existingClaim: frigate-media
  resources:
    requests:
      gpu.intel.com/i915: 1
    limits:
      gpu.intel.com/i915: 1
  securityContext:
    privileged: true
