apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
spec:
  secretName: wildcard-tls
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
  commonName: "neils.house"
  dnsNames:
    - "neils.house"
    - "*.neils.house"
