{{- define "baseApp" -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ required "name is required" .name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ .name }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: {{ .group }}/{{ .name }}
    targetRevision: master
    repoURL: https://github.com/nrlulz/homelab
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
    syncOptions:
      CreateNamespace: "true"
      RespectIgnoreDifferences: "true"
    managedNamespaceMetadata:
      annotations:
        volsync.backube/privileged-movers: "true"
  ignoreDifferences:
    ignoreReplicationSourceTriggerSchedule:
      kind: ReplicationSource
      group: volsync.backube
      jsonPointers:
        - /spec/trigger/schedule
{{- end -}}

{{- range $group, $apps := .Values.apps -}}
  {{- range $app := $apps -}}
    {{- $manifest := fromYaml (include "baseApp" (dict "group" $group "name" $app.name)) -}}
    {{- $_ := set $manifest "metadata" (mergeOverwrite $manifest.metadata ($app.metadata | default dict)) -}}
    {{- $_ := set $manifest "spec" (mergeOverwrite $manifest.spec ($app.spec | default dict)) -}}

    {{/* sync options map to list */}}
    {{- $syncOptions := list -}}
    {{- range $k, $v := $manifest.spec.syncPolicy.syncOptions -}}
      {{- $syncOptions = append $syncOptions (printf "%s=%s" $k $v) -}}
    {{- end -}}
    {{- $_ := set $manifest.spec.syncPolicy "syncOptions" $syncOptions }}

    {{/* ignore differences map to list */}}
    {{- $ignoreDifferences := list -}}
    {{- range $_, $v := $manifest.spec.ignoreDifferences -}}
      {{- $ignoreDifferences = append $ignoreDifferences $v -}}
    {{- end -}}
    {{- $_ := set $manifest.spec "ignoreDifferences" $ignoreDifferences }}

---
{{ toYaml $manifest }}

  {{ end -}}
{{- end }}
