{{- range $group, $apps := .Values.apps}}
{{- range $app := $apps }}
{{ $app = mergeOverwrite (deepCopy $.Values.allApps) $app }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ required "name is required" $app.name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ $app.namespace | default $app.name }}
    server: {{ $.Values.spec.destination.server }}
  project: default
  source:
    path: {{ if $app.path }}{{ $app.path }}{{ else }}{{ $group }}/{{ $app.name }}{{ end }}
    targetRevision: {{ $app.targetRevision | default $.Values.spec.source.targetRevision }}
    repoURL: {{ $app.repoURL | default $.Values.spec.source.repoURL }}
    {{- if $app.source }}
      {{- $app.source | toYaml | nindent 4 }}
    {{- end }}
  syncPolicy:
    automated: {{- $app.automatedSync | toYaml | nindent 6 }}
    retry:
      limit: 10
      backoff:
        duration: 1m
        factor: 2
        maxDuration: 16m
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata: {{- $app.managedNamespaceMetadata | toYaml | nindent 6 }}
  ignoreDifferences:
    - kind: ReplicationSource
      group: volsync.backube
      jsonPointers:
        - /spec/trigger/schedule
    - kind: Application
      group: argoproj.io
      jsonPointers:
        - /status
{{- if $app.ignoreDifferences }}
    {{- $app.ignoreDifferences | toYaml | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
