minio:
  mode: standalone
  environment:
    MINIO_STORAGE_CLASS_RRS: EC:0
    MINIO_STORAGE_CLASS_STANDARD: EC:0
    MINIO_UPDATE: "off"
  securityContext:
    runAsUser: 473
    runAsGroup: 473
    fsGroup: 473
  persistence:
    existingClaim: minio
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
    hosts:
      - s3.internal.neils.house
  consoleIngress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
    hosts:
      - minio.internal.neils.house
  users:
    - accessKey: admin
      existingSecret: minio-admin-password
      existingSecretKey: password
      policy: consoleAdmin
    - accessKey: volsync
      existingSecret: minio-volsync-password
      existingSecretKey: password
      policy: volsync-rw
