apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
spec:
  encryptedData:
    clientSecret: AgAuxmELMmp+veTn7kBv9/tUwwQXdgZ3k6VvAbN033HOW6j4wOtW9XwyBR+4HAafa9hVqblYJ2txImpEcJW6Vmtkr8kQvuuFCrBDDtJC1pOhwJ3lMOqPQ5f6zHaijrch33PTvQ/MPLYbqiOxeg85xOQnmCTg1bE1h266ilWNT5o2zkIB+VXxKN3PxKWEdJbhuZeD5XK4CDZsgyIVey+dOHr5Hf1OD/61XwjIP/AYb8BZ9ONnUqYthbPquDNPUUs/NLJM5EY5i3coOG1en5N11QjNUzQLY0dedKF87zCzAZMPfF2C7pzEbYY6z0+FGUdbvn0koCYmTkbyfJThcF4KrdwWKJUMvt3TKiYgYskyb7sd1Q5RgBxbNpJUCXAKhLEVa4NQawzhCV/rRevRNATr70WCQLq5AtxJZB4AY5va14uOfDHfG+VyQiog5MtSI6lw7ICEmNYX2Fv2XjxlnOxbFhpf4aBd90NYxgnMMvXKarmPjX1rxJH3rCeS5TFPLOjEUznPsBUOakicMydyIU+1L0TcfSYtB/+tXNLaxoGcOe3K83kB6Y8l1HvN5tKvUgFn5GdLKn6QLLNpkf+HfFzaOfHxUJFi2BS2cX315+gp/dzR024mgBTmvb4MsWXEVsi4I+74dfv+g40Qj50WZORNjyPYyMM6ULS7ws+o3Hi4DibKEtAdMrRc1UKJ1Epr80tcIRqnuraYZMlcA/dWk/THOYFdiEd8KOSB/EPQvhOrQAsQ7A==
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
