apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-webhook
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: secret
      remoteRef:
        key: ARGOCD_GITHUB_WEBHOOK_SECRET
