apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  ports:
    - protocol: TCP
      port: 6767
      targetPort: 6767

---
apiVersion: v1
kind: Endpoints
metadata:
  name: bazarr
subsets:
  - addresses:
      - ip: 192.168.1.30
    ports:
      - port: 6767

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
spec:
  rules:
    - host: bazarr.neils.house
      http:
        paths:
          - backend:
              service:
                name: bazarr
                port:
                  number: 6767
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - bazarr.neils.house
