apiVersion: v1
kind: Service
metadata:
  name: homeassistant
spec:
  ports:
    - protocol: TCP
      port: 8123
      targetPort: 8123

---
apiVersion: v1
kind: Endpoints
metadata:
  name: homeassistant
subsets:
  - addresses:
      - ip: 192.168.1.24
    ports:
      - port: 8123

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
spec:
  rules:
    - host: ha.neils.house
      http:
        paths:
          - backend:
              service:
                name: homeassistant
                port:
                  number: 8123
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - ha.neils.house
