apiVersion: v1
kind: Service
metadata:
  name: overseerr
spec:
  ports:
    - protocol: TCP
      port: 5055
      targetPort: 5055

---
apiVersion: v1
kind: Endpoints
metadata:
  name: overseerr
subsets:
  - addresses:
      - ip: 192.168.1.30
    ports:
      - port: 5055

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr
spec:
  rules:
    - host: requests.neils.house
      http:
        paths:
          - backend:
              service:
                name: overseerr
                port:
                  number: 5055
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - requests.neils.house
