apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878

---
apiVersion: v1
kind: Endpoints
metadata:
  name: radarr
subsets:
  - addresses:
      - ip: 192.168.1.30
    ports:
      - port: 7878

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
spec:
  rules:
    - host: radarr.neils.house
      http:
        paths:
          - backend:
              service:
                name: radarr
                port:
                  number: 7878
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - radarr.neils.house
