apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989

---
apiVersion: v1
kind: Endpoints
metadata:
  name: sonarr
subsets:
  - addresses:
      - ip: 192.168.1.30
    ports:
      - port: 8989

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
spec:
  rules:
    - host: sonarr.neils.house
      http:
        paths:
          - backend:
              service:
                name: sonarr
                port:
                  number: 8989
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - sonarr.neils.house
