prometheus:
  server:
    ingress:
      enabled: true
      ingressClassName: internal
      hosts:
        - prometheus.internal.neils.house
    global:
      scrape_interval: 10s
    persistentVolume:
      size: 64Gi
      storageClass: longhorn-ephemeral
    priorityClassName: system-cluster-critical
    resources:
      limits:
        cpu: 800m
        memory: 4Gi
      requests:
        cpu: 800m
        memory: 4Gi
  extraScrapeConfigs: |
    - job_name: 'truenas'
      metric_relabel_configs:
        - source_labels: []
          target_label: node
          replacement: nas
      static_configs:
        - targets:
          - 192.168.1.10:9100
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  prometheus-node-exporter:
    priorityClassName: system-node-critical
