apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
spec:
  addresses:
    - 192.168.1.25-192.168.1.29

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
