apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-movies
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  nfs:
    path: /mnt/media/movies
    server: nas.internal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-movies
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: bazarr-movies

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bazarr-series
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  nfs:
    path: /mnt/media/series
    server: nas.internal

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-series
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  volumeName: bazarr-series
