apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bazarr
spec:
  serviceName: bazarr
  selector:
    matchLabels:
      app: bazarr
  replicas: 0
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:1.4.3
          ports:
            - containerPort: 6767
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Los_Angeles"
          volumeMounts:
            - name: data
              mountPath: /config
            - name: movies
              mountPath: /movies
            - name: series
              mountPath: /tv
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bazarr-data
        - name: movies
          persistentVolumeClaim:
            claimName: bazarr-movies
        - name: series
          persistentVolumeClaim:
            claimName: bazarr-series
