pgcluster:
  image: ghcr.io/cloudnative-pg/postgresql:18.6@sha256:a66f9e4c34950b78668fa4741bf55e6a58227cc31a6e60c128f2ce1d4c072928
  databaseName: photoview
  generation: 1

  cluster:
    storage:
      size: 2Gi

app-template:
  defaultPodOptions:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
  controllers:
    photoview:
      containers:
        photoview:
          image:
            repository: docker.io/photoview/photoview
            tag: 2.4.0@sha256:43cea2673e3912b843cb9508064d41f1e76fc4908ee25e914b5e791e916939a9
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          env:
            PHOTOVIEW_DATABASE_DRIVER: "postgres"
            PHOTOVIEW_LISTEN_IP: "0.0.0.0"
            PHOTOVIEW_MEDIA_CACHE: "/cache"
            PHOTOVIEW_POSTGRES_URL:
              valueFrom:
                secretKeyRef:
                  name: photoview-cluster-v1-app
                  key: uri
          probes:
            startup:
              enabled: true
            liveness:
              enabled: true
            readiness:
              enabled: true
  service:
    photoview:
      controller: photoview
      ports:
        http:
          port: 80
  ingress:
    photoview:
      className: internal
      hosts:
        - host: photoview.internal.neils.house
          paths:
            - path: /
              service:
                identifier: photoview
                port: http
  persistence:
    cache:
      storageClass: longhorn-ephemeral
      suffix: cache
      size: 8Gi
      accessMode: ReadWriteOnce
    photos:
      type: nfs
      server: nas.internal
      path: /mnt/data/photos
      globalMounts:
        - path: /mnt/data/photos
          readOnly: true
