apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: LOKI_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: LOKI_SECRET_ACCESS_KEY
