apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    AWS_SECRET_ACCESS_KEY: AgC067tdERCtvoeLaovWVs5M0NyxafTdBieyIjLu4s+yiQDpxq7sFO5ePXroE+gH/5Ygc/SqpWPx8GXuKU1eXPwKyeVULlx+7duYRnsqz/qk5WAXEcedBYpOnswH8Syg5xTibtC7Oar9x0WCc7w6cWqBjOxRvrzMYMIB4fBmudDe0hAwSd77h+h32h1HgAH4kCjo2VeXVYzYro7rCmbO+BJqHg4lPzTkuttdQRtW1Bw1UTqH/ne7PBwJBv7QdJu+aV2ForwvGjeaWw1juh6iwq5qOo5U9A2QkerxmKPrvmwRtkLvS6koiw21xTifBIwv397m58OFpVxF1N0OaY0bECcD1A/AYgsgczaEzMu90ytarCWNbP5X57c/SO36kuTyXfbiLoo8xLBozd9FxWstYIsTwMuXB2+8QDLe/fAfHf6nhNvww2wVtTBebGr+jBgIiG45LUV1IHv7SVgWh0LiQVS4iwBq0PtZIbJcigQvgCixAbsFzKkXroCRCOYf6hwkJOw4DV6RkdB8MHdXh0xigwWVD4zX+D8eDxYruuTBcFvgU3ZonpyvEXTb0Fyn7cT9o3PDtEsapZeX/Tdg+efAup1MjnZR3wDbR1Bl8OKWQI2rjzGvvHAUrRsEMdeS2vXfiMp5SvQevdV3qFEZpkhtP6hw5WJSgp7MpLu57AjcgkTSi55GNqpxtRCoFBxTEXKghvxH4sFKhffj+bKixjtrnXuzmyTh9Q==
