apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nparker2172@gmail.com
    privateKeySecretRef:
      name: letsencrypt-private-key
    solvers:
      - dns01:
          cloudflare:
            email: nparker2172@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: cloudflare-api-token
        selector:
          dnsZones:
            - "neils.house"
