apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: CERT_MANAGER_CLOUDFLARE_API_TOKEN
