apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
spec:
  encryptedData:
    cloudflare-api-token: AgBUyP+vINkbIvICVOHdNyZpcdPVc+4xHaNJlj7btf8ngvzpxqJSTcSB5/XKECYndzT6XDbIIPI6j7eyx2MDoC65BLQnaO8C4UsRJx5kF8ebga2hJJk+RYeDXo/ZNQsDx9WP9Tbo1pjuUwSKm8rBqXQgV4uMTq9IsAoJb1hRgV4RsKAjU8nzCbYu9J2ZO8ezvAPBYylCnZzNGn9LWGrBVo/wz7LUWJV51L+t4jZqaXQoJxbl7CuopMA5Z87xbjv+IPQxRXkF73hJo+/c4SSOgPAN4Wy61ECj8Jqp5OA3qW6mfzqRdUsnhCvMvuxqkeGgRHOLMJ72gp3pMDPKMV5D8nCGzMSdJZ8as73FHoiIW0RO6aGVQAviDeq3SwnIrZuJxPGJTh279JWQzpXUobfHAqVzq/yjb+Ulp6SdZDxgwjKzjJZXbf6lrTEMgKftMfHAxR+FcpH8bkmQuzM46daIeFSHXIWt2JjVO0ireuy/0oeEROfFy3NW4cafu1iy7wJlAocztj6oniakCsKTcT0uuGSr8i7K4dhvg/a4AoItFiZRJjR8sJLx+vMNr8Nch5dT9UMOIpPlNyvF1MOLJcG7i2ch32wEOiFnQiYZpg6k8R4I5zmi/wWGRuHgbAKLw5jEjSld3rVf5Op8YQE/jx3hwQqQ3fCGPzIpICQB+RvLtTnMLCjGrK8oMG1nqXbQggdUSe+/xvwBgGcQ1RDqnGly6+D7UfHyBnH8H3A9UvLK94LtEgVxqMezdk27
