apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wireguard
spec:
  encryptedData:
    PASSWORD_HASH: AgBneO3tcUhIK6T7LG74eQG1rDIsvnLVhvPCcEukWPPIUomHM4Y83u/cVlxJKs2p0EQosV82G4waNOE74dOFrJosSZGJxcO7FKmzAnpv1rEnaEFAFh66obfpmNI4VXIYOjO8T2f4IZR2aCrFKb7lXnJbmW1XvrHXKw2iRGnwmUrdhf/5I6wFyJOQ4RHtiPaj+YG0/p9pZ/k+t1PINEshFbKqX1OEZPvrQHTwCjcYoEEGATTXNixXrRjeXzMx7GOdFtVC9PLpAIoY/l1KHrHnKw38K0o84gmJEuOmTg7fnONpqxtCF9+hQGjn3P2ZJIJ+TPltBTwNb0dZnWZ7dqLfbwpOQnevTlEz6tvuezxP2w6TczewFmvXgZBIr5PDEVaJX2k6vpF1AkuiEJsVKgStj/515dMAgpWZ2vNW5lbJg88SAHbXNKy3kZ6C5Y6Lu1mUqMYjmjVPGoI38T4uD4Vpg2q5n60rW7kr6RGQTAZsIB80l08seUe//4tA0njS3mF+lPl9zj7qRuCduobIs4bXwJ39+PjTOphR/uNUiK8GOqhdWewzMx6UNdmNmQmbhw5ittfsfhgUi6HLJxM3WPBJKVYSqpLTcaGZfSs+vZ2uzCTA3L5tCpKUWcj2dULlUHRCcbZBmyGmv0F3KSGPDJYQ6KDJEhtb22ur8cLg7VqZ/CW5zDarXAgV2Pg6IvP7SkUbhTvRBC7DXWWBJe0ZVlVZbG/0Dn7dVkHGoXj04GX3KbWARuh6vhnH+Y8iHg8A95Vt7t2vmcK50XekV+gL3q4=
