apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-ingest
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
  storageClassName: longhorn-standard
