apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-app
  namespace: argocd
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  source:
    repoURL: "https://github.com/nrlulz/homelab.git"
    path: apps
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
