apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 6.7.18
    helm:
      releaseName: argocd
      values: |
        global:
          domain: argocd.internal.neils.house
        configs:
          params:
            server.insecure: true
        server:
          ingress:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: default-internal-network-only@kubernetescrd
            extraTls:
              - hosts:
                  - argocd.internal.neils.house
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
