apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: 1.6.1
      helm:
        valuesObject:
          ingress:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: default-internal-network-only@kubernetescrd
            host: longhorn.internal.neils.house
            tls: true
            tlsSecret: ""
          longhornUI:
            replicas: 1
          defaultSettings:
            defaultReplicaCount: 1
          csi:
            attacherReplicaCount: 1
            provisionerReplicaCount: 1
            resizerReplicaCount: 1
            snapshotterReplicaCount: 1
          persistence:
            defaultClassReplicaCount: 1
          preUpgradeChecker:
            jobEnabled: false
    - repoURL: https://github.com/nrlulz/homelab.git
      path: apps/longhorn
      targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
