apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-common
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nrlulz/homelab.git
    path: apps/media-common
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
