apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.21.0
    helm:
      values: |
        server:
          ingress:
            enabled: true
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: default-internal-network-only@kubernetescrd
            hosts:
              - prometheus.internal.neils.house
            tls:
              - hosts:
                  - prometheus.internal.neils.house
          global:
            scrape_interval: 15s
          persistentVolume:
            size: 10Gi
            storageClassName: longhorn
          priorityClassName: system-cluster-critical
          retention: 7d
        alertmanager:
          enabled: false
        prometheus-pushgateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
