apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr
spec:
  secretStoreRef:
    name: bitwarden
    kind: ClusterSecretStore
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: SONARR_API_KEY
