apiVersion: v2
name: paperless-ngx
version: 0.0.0
dependencies:
  - alias: pvc-data
    name: pvc
    version: 0.0.0
    repository: file://../../charts/pvc
  - alias: pvc-media
    name: pvc
    version: 0.0.0
    repository: file://../../charts/pvc
  - alias: pvc-redisdata
    name: pvc
    version: 0.0.0
    repository: file://../../charts/pvc
  - name: pgcluster
    version: 0.0.0
    repository: file://../../charts/pgcluster
  - alias: gotenberg
    name: app-template
    version: 4.5.0
    repository: oci://ghcr.io/bjw-s-labs/helm
  - alias: redis
    name: app-template
    version: 4.5.0
    repository: oci://ghcr.io/bjw-s-labs/helm
  - alias: tika
    name: app-template
    version: 4.5.0
    repository: oci://ghcr.io/bjw-s-labs/helm
  - alias: server
    name: app-template
    version: 4.5.0
    repository: oci://ghcr.io/bjw-s-labs/helm
