apiVersion: v2
name: paperless-ngx
version: 0.0.0
dependencies:
  - name: pvc
    version: 0.0.0
    repository: file://../../charts/pvc
  - name: pgcluster
    version: 0.0.0
    repository: file://../../charts/pgcluster
  - alias: gotenberg
    name: app-template
    version: 5.1.0
    repository: oci://ghcr.io/bjw-s-labs/helm
  - alias: tika
    name: app-template
    version: 5.1.0
    repository: oci://ghcr.io/bjw-s-labs/helm
  - alias: server
    name: app-template
    version: 5.1.0
    repository: oci://ghcr.io/bjw-s-labs/helm
  - name: valkey
    repository: oci://ghcr.io/valkey-io/valkey-helm
    version: 0.12.0
