apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: paperless-inbox
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - iocharset=utf8
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
    - mfsymlinks
    - cache=strict
    - noserverino
    - forceuid
  csi:
    driver: smb.csi.k8s.io
    # volumeHandle format: {smb-server-address}#{sub-dir-name}#{share-name}
    # make sure this value is unique for every share in the cluster
    volumeHandle: c-smb.internal/paperless_inbox##
    volumeAttributes:
      source: //c-smb.internal/paperless_inbox
    nodeStageSecretRef:
      name: cifs-credentials-paperless-ngx
      namespace: paperless-ngx

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: paperless-inbox-pvc
  namespace: paperless-ngx
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: paperless-inbox
  storageClassName: smb
