apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-admin-password
spec:
  encryptedData:
    password: AgC3WzV+HAsnfpr2+Ai96dYEJa2di7r5jbcIWeTsOQ85OCDvp1JAgqLW1MYimZZrkt4eoYQtAjXSquCa8trq2XiBvtSCMRcJdCx06Eoau5J4Yf0csfHioB37iqiMYrjCLc6aj6p2o09meEdbfarqEG83EUAFeIXnukLDZm06M7wFBauSpR9ljgLYwt6yoeLTIBSL8t/DH+rAlAq75aJ+LEZp5t/hVXelW4Ipl1MEO7cxjT79/Z+1Kq0LNPFb3PYCF7tIF1pRYBXS/v4cqTfGgYt7CXbREFfgIY5Sf/T3XoFwLBffIg96SKAa1ZMv2fcpiqY8LvU7Jd6s7Wd+XEYdORjbBo3lOQfVUyXBm7026DHIzewt/2iQH4KIl0wfWYvRKI2QhfalUNYjiW5Zfyyb8UhBP0rJWR8JxQCXvrd+JCfmb8HDhGlLx+BTLjYXrZBRajcEZNB2EjwPMNPcjHIVUH9LCyFKCxreU7xlBEDr0e2t+o7yTCC6wqqAGmK/yO1T0IycutTMA5P9yuArHkfSokFW3DUWv3r2mWOaJShEoRllnkUJcfxf8aUBbnrbiFFJc4QuUO8uosBPaY/mi9jTw/gRJ93syQ1dTxDxBY4TM4XXgR2vCZoDkyAtdxz3rS5rmh9s+h2Ekh7wdo6ifSyb4m9SAW4I2TIwMTamm43AxbTfHlJDmfmfBCBIPejHQluatGBC5qVDG9Ogq1BclD6ae2OBRLjsqw==

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-volsync-password
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    password: AgAMWoG/XRO0Qj05YOtTI+d5BYPaaTzRh1eXhTE2UMnp5XMYvunRG72PbygnJ8gT/s06FZQkmeDAjjfeCAKZtGIYOt2/EmpDHLdps0XY4g//E8svDBer4xpgYMrlVkQBLdzw1dF7v3ukc2e0oVBNLAi7KJ2+lDgGdEhVdjuniJTr0obVJbpOtJbY20HNG+xZLmMqRziePgdhMVypdi1E1soNdEmaJhTPyY9rNUsQTpetg36OeAIi8TGTyAcvo8mOf8CBq4YhI0kv+lW4KXal+ejc+mZSWe6Ao6Q6PkrqhxER6X6efeSFi7YfWbTRDmjCFEQwDM7/CUmdzwWEkSfHsM16Rv3HJNxpfw3EHRpL04XfJMWlWI6xdNQaaTK/tqcZ+Bu7o6BNMmVwfU02FIOeoncouDCiCC/JJWv1/EWUaAWSHDIVG1RB8HlYEmNs3pybEyqGkxp50r/Og9kZCgn4EUh2t7AfxkgOMzCc7Dt8Qf3oQJyIyUMRWGAvBCy1+YfqMOI0D9tcrhVrV8Qf/t0JUR714uUL5gQtFdY090lVssqEcm8XSC+XYoy82f7s5PLQzsgfaEiZIdyOi/vMIC6/FEseOIOB9WwER3Z3s9tp0XfzQfzwr8Ll53ciKxJksT2PEURtIC2n3VMg7Hlu6zfWqes/NQFkW2Linw4OqqPHvtGm/wcXNzgY5DdKguHNcbPIlyhIVTFQpJQE4uecrDLEsEyBMd4zrg==
