apiVersion: v2
name: argocd
version: 0.0.0
sources:
  - https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
  - https://github.com/argoproj/argo-cd
dependencies:
  - name: argo-cd
    version: 9.4.14
    repository: oci://ghcr.io/argoproj/argo-helm
  - name: argocd-apps
    version: 2.0.4
    repository: oci://ghcr.io/argoproj/argo-helm
    condition: argocd-apps.enabled
