argo-cd:
  global:
    domain: argocd.internal.neils.house
  configs:
    params:
      server.insecure: true
  server:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.1.0/24
  dex:
    enabled: false
argocd-apps:
  applicationsets:
    root:
      namespace: argocd
      generators:
        - git:
            repoURL: &repoURL https://github.com/nrlulz/homelab
            revision: &revision v2
            directories:
              - path: system/*
              - path: apps/*
      template:
        metadata:
          name: "{{path.basename}}"
        spec:
          destination:
            name: in-cluster
            namespace: "{{path.basename}}"
          project: default
          source:
            repoURL: *repoURL
            path: "{{path}}"
            targetRevision: *revision
          syncPolicy:
            retry:
              limit: 10
              backoff:
                duration: 1m
                factor: 2
                maxDuration: 16m
            syncOptions:
              - CreateNamespace=true
          ignoreDifferences:
            - kind: CustomResourceDefinition
              group: apiextensions.k8s.io
              name: bgppeers.metallb.io
              jsonPointers:
                - /spec/conversion/webhook/clientConfig/caBundle
