argo-cd:
  global:
    domain: argocd.internal.neils.house
  configs:
    cm:
      resource.customizations.ignoreDifferences.volsync.backube_ReplicationSource: |
        jsonPointers:
          - /spec/trigger/schedule
    params:
      server.insecure: true
    secret:
      githubSecret: "$argocd-webhook:secret"
  server:
    ingress:
      enabled: true
      ingressClassName: internal
  dex:
    enabled: false
argocd-apps:
  enabled: true
  applications:
    cluster:
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/nrlulz/homelab
        targetRevision: master
        path: cluster
      destination:
        name: in-cluster
        namespace: argocd
      ignoreDifferences:
        - kind: Application
          group: argoproj.io
          jsonPointers:
            - /status
