argo-cd:
  global:
    domain: argocd.internal.neils.house
    image:
      tag: v3.2.0-rc2
  configs:
    params:
      controller.diff.server.side: true
      server.insecure: true
    secret:
      githubSecret: "$argocd-webhook:secret"
  server:
    ingress:
      enabled: true
      ingressClassName: internal
  dex:
    enabled: false
argocd-apps:
  enabled: true
  applications:
    cluster:
      namespace: argocd
      project: default
      source:
        repoURL: https://github.com/nrlulz/homelab
        targetRevision: master
        path: cluster
      destination:
        name: in-cluster
        namespace: argocd
      ignoreDifferences:  # necessary?
        - kind: Application
          group: argoproj.io
          jsonPointers:
            - /status
