ingress-nginx:
  controller:
    kind: DaemonSet
    watchIngressWithoutClass: true
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        metallb.io/loadBalancerIPs: 192.168.1.29
    extraArgs:
      default-ssl-certificate: ingress-nginx/wildcard-tls
    config:
      force-ssl-redirect: true
      proxy-body-size: 0
      worker-shutdown-timeout: 60s
    metrics:
      enabled: true
    podAnnotations:
      prometheus.io/port: "10254"
      prometheus.io/scrape: "true"
