ingress-nginx:
  controller:
    kind: DaemonSet
    ingressClassResource:
      name: external
      default: false
      controllerValue: k8s.io/ingress-nginx-external
    service:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        metallb.io/loadBalancerIPs: 192.168.1.29
    extraArgs:
      default-ssl-certificate: ingress-nginx/wildcard-tls
    config:
      force-ssl-redirect: true
      proxy-body-size: 0
      proxy-read-timeout: 300
      proxy-send-timeout: 300
      worker-shutdown-timeout: 60s
    metrics:
      enabled: true
    podAnnotations:
      prometheus.io/port: "10254"
      prometheus.io/scrape: "true"
