# https://github.com/external-secrets/bitwarden-sdk-server/blob/main/README.md#certificates
# https://github.com/external-secrets/bitwarden-sdk-server/blob/main/hack/bitwarden-certificate.yaml
# tl;dr: the bitwarden-sdk-server subchart expects a TLS secret named bitwarden-tls-certs to exist

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-tls-certs
spec:
  secretName: bitwarden-tls-certs
  dnsNames:
    - bitwarden-sdk-server.external-secrets.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    rotationPolicy: Always
    size: 2048
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-issuer
