# https://dag-andersen.github.io/argocd-diff-preview/github-actions-workflow/

name: Argo CD Diff Preview

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          path: pull-request

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          ref: master
          path: master

      - name: Render chart-of-apps
        run: |
          helm template master/cluster > master/rendered.yaml
          helm template pull-request/cluster > pull-request/rendered.yaml

      - name: Extract ArgoCD chart version from master branch
        run: |
          version=$(yq e '.dependencies[] | select(.name == "argo-cd") | .version' master/system/argocd/Chart.yaml)
          echo "ARGOCD_CHART_VERSION=$version" >> $GITHUB_ENV

      - name: Generate Diff
        env:
          ARGOCD_DIFF_PREVIEW_IMAGE: docker.io/dagandersen/argocd-diff-preview:v0.2.10@sha256:47d105677d377d29c0a23a1e72bf6efd68e81e4ea73b9d4f16ecae1b09b26460
          KIND_NODE_IMAGE: docker.io/kindest/node:v1.36.1@sha256:3489c7674813ba5d8b1a9977baea8a6e553784dab7b84759d1014dbd78f7ebd5
        run: |
          docker run \
            --network=host \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $(pwd)/master:/base-branch \
            -v $(pwd)/pull-request:/target-branch \
            -v $(pwd)/output:/output \
            -e ARGOCD_CHART_VERSION=${{ env.ARGOCD_CHART_VERSION }} \
            -e BASE_BRANCH=master \
            -e DIFF_IGNORE="checksum/" \
            -e IGNORE_RESOURCES="*:CustomResourceDefinition:*" \
            -e TARGET_BRANCH=refs/pull/${{ github.event.number }}/merge \
            -e REPO=${{ github.repository }} \
            -e KIND_OPTIONS="--image=${KIND_NODE_IMAGE}" \
            -e FILE_REGEX="rendered\.yaml" \
            -e DEBUG=true \
            ${ARGOCD_DIFF_PREVIEW_IMAGE}

      - name: Post diff as comment
        run: |
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md --edit-last || \
          gh pr comment ${{ github.event.number }} --repo ${{ github.repository }} --body-file output/diff.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: output
          path: output/
